# Generated by Django 3.1.5 on 2022-07-05 11:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Areas', '0003_auto_20220705_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('purchase_description', models.TextField()),
                ('purchase_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('price', models.PositiveBigIntegerField()),
                ('stock_quantity', models.PositiveBigIntegerField()),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of created')),
            ],
            options={
                'db_table': 'bms_assets_details',
            },
        ),
        migrations.CreateModel(
            name='AssetsService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=254)),
                ('provider_details', models.JSONField(blank=True, default=dict, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of created')),
            ],
            options={
                'db_table': 'bms_assets_service',
            },
        ),
        migrations.CreateModel(
            name='AssetsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of created')),
            ],
            options={
                'db_table': 'bms_assets_type',
            },
        ),
        migrations.CreateModel(
            name='ServiceForAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_information', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('in-active', 'In-active')], max_length=15)),
                ('assets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreAssets_Management.assetsdetails')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreAssets_Management.assetsservice')),
            ],
            options={
                'db_table': 'bms_service_for_assets',
            },
        ),
        migrations.CreateModel(
            name='ManageAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.PositiveBigIntegerField()),
                ('alert_message', models.CharField(max_length=254)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of created')),
                ('assets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreAssets_Management.assetsdetails')),
                ('sub_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Areas.subarea')),
            ],
            options={
                'db_table': 'bms_manage_assets',
            },
        ),
        migrations.AddField(
            model_name='assetsdetails',
            name='assets_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreAssets_Management.assetstype'),
        ),
    ]
