# Generated by Django 3.1.5 on 2022-07-21 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20220705_1710'),
        ('StoreAssets_Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageassets',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.userbms'),
        ),
        migrations.AlterField(
            model_name='assetsdetails',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='assetsdetails',
            name='stock_quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='number of quantity'),
        ),
        migrations.AlterField(
            model_name='manageassets',
            name='stock_quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='number of quantity'),
        ),
    ]
