# Generated by Django 3.1.5 on 2022-07-04 04:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Areas', '0002_auto_20220629_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(error_messages={'unique': 'A user with that email address  already exists.'}, max_length=254, unique=True)),
                ('password', models.CharField(max_length=254)),
                ('status', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of joined')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Date of modified')),
            ],
            options={
                'verbose_name': 'User BMS',
                'verbose_name_plural': 'Users BMS',
                'db_table': 'bms_users',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('permission_ids', models.JSONField(blank=True, default=list, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of created')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Date of modified')),
            ],
            options={
                'db_table': 'bms_roles',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of created')),
            ],
            options={
                'db_table': 'bms_user_types',
            },
        ),
        migrations.CreateModel(
            name='UserVisitorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_no', models.CharField(max_length=16)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of created')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Date of modified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.userbms')),
            ],
            options={
                'db_table': 'bms_visitor_details',
            },
        ),
        migrations.CreateModel(
            name='UserStaffDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('phone_no', models.CharField(max_length=16)),
                ('birthdate', models.DateField()),
                ('address', models.TextField()),
                ('access_area', models.JSONField(blank=True, default=list, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of created')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Date of modified')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Areas.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.userbms')),
            ],
            options={
                'db_table': 'bms_staff_details',
            },
        ),
        migrations.AddField(
            model_name='userbms',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.userrole'),
        ),
        migrations.AddField(
            model_name='userbms',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.usertype'),
        ),
    ]
