# Generated by Django 3.1.5 on 2022-06-24 10:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of created')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Date of modified')),
            ],
            options={
                'db_table': 'bms_department_master',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of created')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Date of modified')),
            ],
            options={
                'db_table': 'bms_floor_master',
            },
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image_path', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of created')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Date of modified')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Areas.department')),
            ],
            options={
                'db_table': 'bms_subArea_master',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Areas.floor'),
        ),
    ]
