# Generated by Django 3.1.5 on 2022-06-29 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Area Department', 'verbose_name_plural': 'Area Departments'},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'verbose_name': 'Area Floor', 'verbose_name_plural': 'Area Floors'},
        ),
        migrations.AlterModelOptions(
            name='subarea',
            options={'verbose_name': 'Area SubArea', 'verbose_name_plural': 'Area SubAreas'},
        ),
    ]
