# Generated by Django 3.1.5 on 2022-07-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Areas', '0002_auto_20220629_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subarea',
            name='image_path',
        ),
        migrations.AddField(
            model_name='subarea',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='subarea',
            name='seating_capacity',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
