# Generated by Django 3.1.5 on 2022-07-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Areas', '0003_auto_20220705_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subarea',
            old_name='image',
            new_name='off_image',
        ),
        migrations.AddField(
            model_name='subarea',
            name='on_image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
