# Generated by Django 3.1.5 on 2022-07-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Areas', '0004_auto_20220706_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subarea',
            name='off_image',
        ),
        migrations.RemoveField(
            model_name='subarea',
            name='on_image',
        ),
        migrations.AddField(
            model_name='subarea',
            name='height',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subarea',
            name='off_image_path',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subarea',
            name='on_image_path',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subarea',
            name='width',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
