# Generated by Django 3.1.5 on 2022-07-04 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BMS_Main', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmshistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='Users.userbms'),
        ),
        migrations.AddField(
            model_name='bmsaccesscontrolrfid',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='Users.userbms'),
        ),
    ]
