# Generated by Django 3.1.5 on 2022-07-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMS_Main', '0003_auto_20220705_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmslocker',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('in-active', 'In-active')], default='in-active', max_length=15),
        ),
    ]
