# Generated by Django 3.1.5 on 2022-07-05 11:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0002_auto_20220705_1710'),
        ('Areas', '0003_auto_20220705_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousekeepingGuardService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('in-active', 'In-active')], max_length=15)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of created')),
            ],
            options={
                'db_table': 'bms_housekeeping_guard_service_master',
            },
        ),
        migrations.CreateModel(
            name='HousekeepingGuardDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TextField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=15)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of created')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HousekeepingAndGuardManagement.housekeepingguardservice')),
                ('sub_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Areas.subarea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.userbms')),
            ],
            options={
                'db_table': 'bms_housekeeping_guard_details',
            },
        ),
    ]
