# Generated by Django 3.1.5 on 2022-07-05 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioAnnouncements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_file', models.FileField(upload_to='audio-announcements')),
                ('description', models.TextField()),
                ('sub_area_ids', models.JSONField(blank=True, default=list, null=True)),
                ('is_recurrence', models.BooleanField()),
                ('reccurence_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('bi-weekly', 'Bi-weekly'), ('monthly', 'Monthly')], max_length=15)),
                ('date', models.DateField()),
                ('play_time', models.TimeField()),
                ('play_after_each_duration', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('in-active', 'In-active')], max_length=15)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of created')),
            ],
            options={
                'db_table': 'bms_audio_announcements',
            },
        ),
    ]
