# Generated by Django 3.1.5 on 2022-07-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioAnnouncementSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioannouncements',
            name='announcement_file',
            field=models.CharField(max_length=255),
        ),
    ]
