# Generated by Django 3.1.5 on 2022-07-04 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Areas', '0002_auto_20220629_1415'),
        ('ConferenceRoomBooking', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceroombooking',
            name='book_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookByUser', to='Users.userbms'),
        ),
        migrations.AddField(
            model_name='conferenceroombooking',
            name='meeting_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Areas.subarea'),
        ),
    ]
