# Generated by Django 3.1.5 on 2022-07-05 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20220705_1710'),
        ('ConferenceRoomBooking', '0002_auto_20220704_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conferenceroombooking',
            old_name='users',
            new_name='attendees',
        ),
        migrations.RenameField(
            model_name='conferenceroombooking',
            old_name='date',
            new_name='meeting_date',
        ),
        migrations.RemoveField(
            model_name='conferenceroombooking',
            name='book_by',
        ),
        migrations.AddField(
            model_name='conferenceroombooking',
            name='amenities',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conferenceroombooking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirm', 'Confirm'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conferenceroombooking',
            name='booking_type',
            field=models.CharField(choices=[('new', 'New'), ('re-schedule', 'Re-schedule')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conferenceroombooking',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.userbms'),
        ),
        migrations.AddField(
            model_name='conferenceroombooking',
            name='meeting_link',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conferenceroombooking',
            name='no_of_attendees',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
