# Generated by Django 3.1.5 on 2022-07-04 04:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of created')),
            ],
            options={
                'verbose_name': 'Device App Type',
                'verbose_name_plural': 'Devices App Type',
                'db_table': 'bms_app_type',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=254)),
                ('is_used', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=15)),
                ('device_information', models.JSONField(blank=True, default=list, null=True)),
                ('status', models.CharField(max_length=10)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of created')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Date of modified')),
            ],
            options={
                'db_table': 'bms_devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceHasUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of created')),
            ],
            options={
                'db_table': 'bms_devices_has_users',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of created')),
            ],
            options={
                'db_table': 'bms_device_type',
            },
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_status', models.CharField(max_length=10)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of created')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Devices.device')),
            ],
            options={
                'db_table': 'bms_device_status',
            },
        ),
    ]
