# Generated by Django 3.1.5 on 2022-07-04 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Areas', '0002_auto_20220629_1415'),
        ('Devices', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.userbms'),
        ),
        migrations.AddField(
            model_name='devicehasuser',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Devices.device'),
        ),
        migrations.AddField(
            model_name='devicehasuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.userbms'),
        ),
        migrations.AddField(
            model_name='device',
            name='app_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Devices.apptype'),
        ),
        migrations.AddField(
            model_name='device',
            name='subArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Areas.subarea'),
        ),
        migrations.AddField(
            model_name='apptype',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Devices.devicetype'),
        ),
    ]
