# Generated by Django 3.1.5 on 2022-07-25 06:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('category_image', models.CharField(max_length=255)),
                ('status', models.JSONField(blank=True, default=dict, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of created')),
            ],
            options={
                'db_table': 'bms_inventory_category',
            },
        ),
        migrations.CreateModel(
            name='ItemDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_description', models.TextField()),
                ('item_image', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('unit', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('minimum_quantity', models.IntegerField()),
                ('status', models.JSONField(blank=True, default=dict, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of created')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryManagement.inventorycategory')),
            ],
            options={
                'db_table': 'bms_item_details',
            },
        ),
        migrations.CreateModel(
            name='ManageInventoryStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255)),
                ('stock_quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of created')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryManagement.itemdetail')),
            ],
            options={
                'db_table': 'bms_manage_inventory_stock',
            },
        ),
    ]
