# Generated by Django 3.1.5 on 2022-07-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycategory',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('in-active', 'In-active')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('in-active', 'In-active')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
