# Generated by Django 3.1.5 on 2022-07-04 04:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=254)),
                ('price', models.PositiveBigIntegerField(verbose_name='food price')),
                ('slug', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of created')),
            ],
            options={
                'db_table': 'bms_food_ordering_food',
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('slug', models.CharField(max_length=254)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of created')),
            ],
            options={
                'db_table': 'bms_food_ordering_category',
            },
        ),
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_ids', models.JSONField(blank=True, default=list, null=True)),
                ('menu_name', models.CharField(max_length=254)),
                ('image', models.ImageField(blank=True, upload_to='menu')),
                ('price', models.PositiveBigIntegerField(verbose_name='menu price')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of created')),
            ],
            options={
                'db_table': 'bms_food_ordering_menu',
            },
        ),
        migrations.CreateModel(
            name='FoodOrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_ids', models.JSONField(blank=True, default=list, null=True)),
                ('amount', models.PositiveBigIntegerField(verbose_name='order amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-process', 'In-process'), ('completed', 'Completed'), ('cancel', 'Cancel')], max_length=15)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Order date and time')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of created')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Date of modified')),
            ],
            options={
                'db_table': 'bms_food_ordering_order_details',
            },
        ),
        migrations.CreateModel(
            name='FoodOrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_amount', models.PositiveBigIntegerField(verbose_name='payment net amount')),
                ('wallet', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], max_length=15)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of created')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodOrdering.foodorderdetails')),
            ],
            options={
                'db_table': 'bms_food_ordering_payment_details',
            },
        ),
    ]
