# Generated by Django 3.1.5 on 2022-07-05 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Areas', '0003_auto_20220705_1710'),
        ('FoodOrdering', '0002_auto_20220704_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodorderdetails',
            old_name='amount',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='foodorderpayment',
            old_name='net_amount',
            new_name='order_amount',
        ),
        migrations.RemoveField(
            model_name='foodorderdetails',
            name='menu_ids',
        ),
        migrations.AddField(
            model_name='foodorderdetails',
            name='from_sub_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Areas.subarea'),
        ),
        migrations.AddField(
            model_name='foodorderdetails',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FoodOrdering.foodmenu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodorderdetails',
            name='quantity',
            field=models.PositiveBigIntegerField(default=1, verbose_name='quantity'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='food',
            table='bms_food_products',
        ),
        migrations.AlterModelTable(
            name='foodcategory',
            table='bms_food_category',
        ),
        migrations.AlterModelTable(
            name='foodmenu',
            table='bms_food_menu',
        ),
        migrations.AlterModelTable(
            name='foodorderdetails',
            table='bms_food_order_details',
        ),
        migrations.AlterModelTable(
            name='foodorderpayment',
            table='bms_food_payment_details',
        ),
    ]
