# Generated by Django 3.1.5 on 2022-07-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodOrdering', '0004_auto_20220715_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodorderdetails',
            name='datetime',
        ),
    ]
